repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: ShellCheck
        files: '\.sh$|gh-workflow-peek$'
        args: ['--severity=warning']