name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run tests
        run: |
          sudo apt-get update
          sudo apt-get install -y jq shellcheck
          ./tests/test.sh
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            
            ## Installation
            ```bash
            gh extension install ${{ github.repository }}
            ```
            
            ## What's Changed
            Please see the commit history for changes.
          draft: false
          prerelease: false