name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq shellcheck
    
    - name: Run shellcheck
      run: shellcheck gh-workflow-peek
    
    - name: Run tests
      run: ./tests/test-simple.sh
    
    # Skip running the actual script since it requires gh authentication
    # The structural tests in test-simple.sh are sufficient for CI

  test-multi-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install jq
    
    - name: Test script structure
      run: |
        # Basic structural tests that don't require gh auth
        head -n 1 gh-workflow-peek | grep -q "#!/usr/bin/env bash"
        grep -q "VERSION=" gh-workflow-peek
        grep -q "check_dependencies" gh-workflow-peek